package APIs_PayLoads;

public class ChaseRequest_PayLoads_RG_20013 {
	public static  String MATCH_WITH_RG_20013(String auditType, String  chartType, String DOS, String DOE, String intendedUse, String accountID, String subAccountID, String cotivitClaimNumber) {		
		String payLoad = "{\r\n"
				+ "  \"ChaseRequest\": {\r\n"
				+ "    \"ChaseRequestHeader\": {\r\n"
				+ "      \"IntendedUse\": \""+intendedUse+"\",\r\n"
				+ "      \"AuditType\": \""+auditType+"\",\r\n"
				+ "      \"ChartType\": \""+chartType+"\",\r\n"
				+ "      \"RelatedChaseID\": \"911\",\r\n"
				+ "      \"ExternalChaseNumber\": \"894986377\",\r\n"
				+ "      \"GlobalWorkforceApproved\": false,\r\n"
				+ "      \"ExpirationDate\": \"2025-12-09\",\r\n"
				+ "      \"MRAvailableInClientSystem\": false,\r\n"
				+ "      \"MRClientSystemDCN\": \"8478579337\",\r\n"
				+ "      \"ProspectiveClaimFlag\": false,\r\n"
				+ "      \"ClientID\": 13,\r\n"
				+ "      \"AccountID\": \""+accountID+"\",\r\n"
				+ "      \"SubAccountId\": \""+subAccountID+"\",\r\n"
				+ "      \"PortalRequestCode\": \"46378\",\r\n"
				+ "      \"PlanName\": \"6\",\r\n"
				+ "      \"PrimaryChaseRequestProviderRole\": \"RenderingProvider\",\r\n"
				+ "      \"ExplicitRequestGroupId\": null\r\n"
				+ "    },\r\n"
				+ "    \"ClaimDetails\": {\r\n"
				+ "      \"CotivitiClaimNumber\": \""+cotivitClaimNumber+"\",\r\n"
				+ "      \"ClaimType\": \"S\",\r\n"
				+ "      \"InNetwork\": true,\r\n"
				+ "      \"ClientClaimNumber\": \"5106326342\",\r\n"
				+ "      \"DateOfServiceStart\": \""+DOS+"\",\r\n"
				+ "      \"DateOfServiceEnd\": \""+DOE+"\",\r\n"
				+ "      \"TotalClaimAmt\": 1666.09,\r\n"
				+ "      \"ProviderSpecialty\": \"test\",\r\n"
				+ "      \"PatientMemberIdx\": 2,\r\n"
				+ "      \"SubscriberMemberIdx\": 1,\r\n"
				+ "      \"BillingProviderIdx\": 1,\r\n"
				+ "      \"RenderingProviderIdx\": 2\r\n"
				+ "    },\r\n"
				+ "    \"ChaseDetails\": {\r\n"
				+ "      \"DOSChartRangeStart1\": \"2022-09-26\",\r\n"
				+ "      \"DOSChartRangeEnd1\": \"2022-09-26\",\r\n"
				+ "      \"DOSChartRangeStart2\": \"2022-09-26\",\r\n"
				+ "      \"DOSChartRangeEnd2\": \"2022-09-26\",\r\n"
				+ "      \"DOSChartRangeStart3\": \"2022-09-26\",\r\n"
				+ "      \"DOSChartRangeEnd3\": \"2022-09-26\",\r\n"
				+ "      \"DOSChartRangeStart4\": \"2022-09-26\",\r\n"
				+ "      \"DOSChartRangeEnd4\": \"2022-09-26\",\r\n"
				+ "      \"DeliveryDate\": \"2022-09-26\",\r\n"
				+ "      \"RetrievalRank\": 8,\r\n"
				+ "      \"HedisMeasureID\": \"HEDIS26\",\r\n"
				+ "      \"MeasurementGap\": \"Measure2\",\r\n"
				+ "      \"SubMeasurementGap\": \"SubMeasure5\",\r\n"
				+ "      \"IsOversampleFlag\": true,\r\n"
				+ "      \"ChasePriority\": \"High\",\r\n"
				+ "      \"RADVEnrolleeID\": \"RADV3354\",\r\n"
				+ "      \"MedicareAdvantagecontractNumber\": \"MA353\"\r\n"
				+ "    },\r\n"
				+ "    \"Members\": [\r\n"
				+ "      {\r\n"
				+ "        \"Member\": {\r\n"
				+ "          \"LastName\": \"ZakirS\",\r\n"
				+ "          \"FirstName\": \"ZRAZ\",\r\n"
				+ "          \"Address1\": \"048 Hinton Loop Apt. 872\",\r\n"
				+ "          \"Address2\": \"Apt. 736\",\r\n"
				+ "          \"City\": \"Kathleenside\",\r\n"
				+ "          \"State\": \"KY\",\r\n"
				+ "          \"Zip\": \"62417\",\r\n"
				+ "          \"DOB\": \"1983-04-18\",\r\n"
				+ "          \"Gender\": \"M\",\r\n"
				+ "          \"SSN\": \"495-92-8935\",\r\n"
				+ "          \"PatientId\": \"4145\",\r\n"
				+ "          \"HICN\": \"716351468\",\r\n"
				+ "          \"ControlNumber\": \"9679\",\r\n"
				+ "          \"MBI\": \"98716\",\r\n"
				+ "          \"RecordNumber\": \"87618\",\r\n"
				+ "          \"ClientMemberID\": \"89225\"\r\n"
				+ "        }\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"Member\": {\r\n"
				+ "          \"LastName\": \"Zakir\",\r\n"
				+ "          \"FirstName\": \"ZR\",\r\n"
				+ "          \"Address1\": \"644 Rachel Ridge Apt. 945\",\r\n"
				+ "          \"Address2\": \"Suite 660\",\r\n"
				+ "          \"City\": \"East Victoriaborough\",\r\n"
				+ "          \"State\": \"MS\",\r\n"
				+ "          \"Zip\": \"14075\",\r\n"
				+ "          \"DOB\": \"2008-02-27\",\r\n"
				+ "          \"Gender\": \"F\",\r\n"
				+ "          \"SSN\": \"790-57-4891\",\r\n"
				+ "          \"PatientId\": \"4906\",\r\n"
				+ "          \"HICN\": \"949290986\",\r\n"
				+ "          \"ControlNumber\": \"1092\",\r\n"
				+ "          \"MBI\": \"77340\",\r\n"
				+ "          \"RecordNumber\": \"26970\",\r\n"
				+ "          \"ClientMemberID\": \"57303\"\r\n"
				+ "        }\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"Providers\": [\r\n"
				+ "      {\r\n"
				+ "        \"Provider\": {\r\n"
				+ "          \"Name\": \"Leblanc Chiropractic, Pc\",\r\n"
				+ "          \"LastName\": \"\",\r\n"
				+ "          \"FirstName\": \"\",\r\n"
				+ "          \"Address1\": \"33259 Anthony Streets Suite 145\",\r\n"
				+ "          \"Address2\": \"Suite 358\",\r\n"
				+ "          \"City\": \"West Jenna\",\r\n"
				+ "          \"State\": \"LA\",\r\n"
				+ "          \"Zip\": \"60923\",\r\n"
				+ "          \"NPI\": \"1578549523\",\r\n"
				+ "          \"TIN\": \"628766168\",\r\n"
				+ "          \"Phone1\": \"147-764-4955\",\r\n"
				+ "          \"Phone2\": \"746-655-2864\",\r\n"
				+ "          \"Phone3\": \"586-128-4316\",\r\n"
				+ "          \"Fax\": \"498-946-3184\",\r\n"
				+ "          \"ClientProviderId\": \"3435\"\r\n"
				+ "        }\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"Provider\": {\r\n"
				+ "          \"Name\": \"Automation Testing QA\",\r\n"
				+ "          \"LastName\": \"Messer\",\r\n"
				+ "          \"FirstName\": \"Michelle\",\r\n"
				+ "          \"Address1\": \"94966 Glass Roads Suite 263\",\r\n"
				+ "          \"Address2\": \"Suite 669\",\r\n"
				+ "          \"City\": \"Davidfurt\",\r\n"
				+ "          \"State\": \"MT\",\r\n"
				+ "          \"Zip\": \"43489\",\r\n"
				+ "          \"NPI\": \"1578549523\",\r\n"
				+ "          \"TIN\": \"967050750\",\r\n"
				+ "          \"Phone1\": \"672-418-1811\",\r\n"
				+ "          \"Phone2\": \"242-244-8446\",\r\n"
				+ "          \"Phone3\": \"366-449-9188\",\r\n"
				+ "          \"Fax\": \"168-994-3569\",\r\n"
				+ "          \"ClientProviderId\": \"619\"\r\n"
				+ "        }\r\n"
				+ "      }\r\n"
				+ "    ]\r\n"
				+ "  }\r\n"
				+ "}";
		return payLoad;
		
	}

	public static  String NO_MATCH_WITH_RG_20013(String intendedUse, String accountID, String subAccountID, String cotivitClaimNumber) {		
		String payLoad = "{\r\n"
				+ "  \"ChaseRequest\": {\r\n"
				+ "    \"ChaseRequestHeader\": {\r\n"
				+ "      \"IntendedUse\": \""+intendedUse+"\",\r\n"
				+ "      \"AuditType\": \"HH\",\r\n"
				+ "      \"ChartType\": \"Billing\",\r\n"
				+ "      \"RelatedChaseID\": \"911\",\r\n"
				+ "      \"ExternalChaseNumber\": \"894986377\",\r\n"
				+ "      \"GlobalWorkforceApproved\": false,\r\n"
				+ "      \"ExpirationDate\": \"2025-12-09\",\r\n"
				+ "      \"MRAvailableInClientSystem\": false,\r\n"
				+ "      \"MRClientSystemDCN\": \"8478579337\",\r\n"
				+ "      \"ProspectiveClaimFlag\": false,\r\n"
				+ "      \"ClientID\": 13,\r\n"
				+ "      \"AccountID\": \""+accountID+"\",\r\n"
				+ "      \"SubAccountId\": \""+subAccountID+"\",\r\n"
				+ "      \"PortalRequestCode\": \"46378\",\r\n"
				+ "      \"PlanName\": \"6\",\r\n"
				+ "      \"PrimaryChaseRequestProviderRole\": \"RenderingProvider\",\r\n"
				+ "      \"ExplicitRequestGroupId\": null\r\n"
				+ "    },\r\n"
				+ "    \"ClaimDetails\": {\r\n"
				+ "      \"CotivitiClaimNumber\": \""+cotivitClaimNumber+"\",\r\n"
				+ "      \"ClaimType\": \"S\",\r\n"
				+ "      \"InNetwork\": true,\r\n"
				+ "      \"ClientClaimNumber\": \"5106326342\",\r\n"
				+ "      \"DateOfServiceStart\": \"2024-09-26\",\r\n"
				+ "      \"DateOfServiceEnd\": \"2024-10-26\",\r\n"
				+ "      \"TotalClaimAmt\": 1666.09,\r\n"
				+ "      \"ProviderSpecialty\": \"test\",\r\n"
				+ "      \"PatientMemberIdx\": 2,\r\n"
				+ "      \"SubscriberMemberIdx\": 1,\r\n"
				+ "      \"BillingProviderIdx\": 1,\r\n"
				+ "      \"RenderingProviderIdx\": 2\r\n"
				+ "    },\r\n"
				+ "    \"ChaseDetails\": {\r\n"
				+ "      \"DOSChartRangeStart1\": \"2022-09-26\",\r\n"
				+ "      \"DOSChartRangeEnd1\": \"2022-09-26\",\r\n"
				+ "      \"DOSChartRangeStart2\": \"2022-09-26\",\r\n"
				+ "      \"DOSChartRangeEnd2\": \"2022-09-26\",\r\n"
				+ "      \"DOSChartRangeStart3\": \"2022-09-26\",\r\n"
				+ "      \"DOSChartRangeEnd3\": \"2022-09-26\",\r\n"
				+ "      \"DOSChartRangeStart4\": \"2022-09-26\",\r\n"
				+ "      \"DOSChartRangeEnd4\": \"2022-09-26\",\r\n"
				+ "      \"DeliveryDate\": \"2022-09-26\",\r\n"
				+ "      \"RetrievalRank\": 8,\r\n"
				+ "      \"HedisMeasureID\": \"HEDIS26\",\r\n"
				+ "      \"MeasurementGap\": \"Measure2\",\r\n"
				+ "      \"SubMeasurementGap\": \"SubMeasure5\",\r\n"
				+ "      \"IsOversampleFlag\": true,\r\n"
				+ "      \"ChasePriority\": \"High\",\r\n"
				+ "      \"RADVEnrolleeID\": \"RADV3354\",\r\n"
				+ "      \"MedicareAdvantagecontractNumber\": \"MA353\"\r\n"
				+ "    },\r\n"
				+ "    \"Members\": [\r\n"
				+ "      {\r\n"
				+ "        \"Member\": {\r\n"
				+ "          \"LastName\": \"ZakirS\",\r\n"
				+ "          \"FirstName\": \"ZRAZ\",\r\n"
				+ "          \"Address1\": \"048 Hinton Loop Apt. 872\",\r\n"
				+ "          \"Address2\": \"Apt. 736\",\r\n"
				+ "          \"City\": \"Kathleenside\",\r\n"
				+ "          \"State\": \"KY\",\r\n"
				+ "          \"Zip\": \"62417\",\r\n"
				+ "          \"DOB\": \"1983-04-18\",\r\n"
				+ "          \"Gender\": \"M\",\r\n"
				+ "          \"SSN\": \"495-92-8935\",\r\n"
				+ "          \"PatientId\": \"4145\",\r\n"
				+ "          \"HICN\": \"716351468\",\r\n"
				+ "          \"ControlNumber\": \"9679\",\r\n"
				+ "          \"MBI\": \"98716\",\r\n"
				+ "          \"RecordNumber\": \"87618\",\r\n"
				+ "          \"ClientMemberID\": \"89225\"\r\n"
				+ "        }\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"Member\": {\r\n"
				+ "          \"LastName\": \"Zakir\",\r\n"
				+ "          \"FirstName\": \"ZR\",\r\n"
				+ "          \"Address1\": \"644 Rachel Ridge Apt. 945\",\r\n"
				+ "          \"Address2\": \"Suite 660\",\r\n"
				+ "          \"City\": \"East Victoriaborough\",\r\n"
				+ "          \"State\": \"MS\",\r\n"
				+ "          \"Zip\": \"14075\",\r\n"
				+ "          \"DOB\": \"2008-02-27\",\r\n"
				+ "          \"Gender\": \"F\",\r\n"
				+ "          \"SSN\": \"790-57-4891\",\r\n"
				+ "          \"PatientId\": \"4906\",\r\n"
				+ "          \"HICN\": \"949290986\",\r\n"
				+ "          \"ControlNumber\": \"1092\",\r\n"
				+ "          \"MBI\": \"77340\",\r\n"
				+ "          \"RecordNumber\": \"26970\",\r\n"
				+ "          \"ClientMemberID\": \"57303\"\r\n"
				+ "        }\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"Providers\": [\r\n"
				+ "      {\r\n"
				+ "        \"Provider\": {\r\n"
				+ "          \"Name\": \"Leblanc Chiropractic, Pc\",\r\n"
				+ "          \"LastName\": \"\",\r\n"
				+ "          \"FirstName\": \"\",\r\n"
				+ "          \"Address1\": \"33259 Anthony Streets Suite 145\",\r\n"
				+ "          \"Address2\": \"Suite 358\",\r\n"
				+ "          \"City\": \"West Jenna\",\r\n"
				+ "          \"State\": \"LA\",\r\n"
				+ "          \"Zip\": \"60923\",\r\n"
				+ "          \"NPI\": \"1578549523\",\r\n"
				+ "          \"TIN\": \"628766168\",\r\n"
				+ "          \"Phone1\": \"147-764-4955\",\r\n"
				+ "          \"Phone2\": \"746-655-2864\",\r\n"
				+ "          \"Phone3\": \"586-128-4316\",\r\n"
				+ "          \"Fax\": \"498-946-3184\",\r\n"
				+ "          \"ClientProviderId\": \"3435\"\r\n"
				+ "        }\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"Provider\": {\r\n"
				+ "          \"Name\": \"Automation Testing phi QA\",\r\n"
				+ "          \"LastName\": \"Messer\",\r\n"
				+ "          \"FirstName\": \"Michelle\",\r\n"
				+ "          \"Address1\": \"94966 Glass Roads Suite 263\",\r\n"
				+ "          \"Address2\": \"Suite 669\",\r\n"
				+ "          \"City\": \"Davidfurt\",\r\n"
				+ "          \"State\": \"MT\",\r\n"
				+ "          \"Zip\": \"43489\",\r\n"
				+ "          \"NPI\": \"1578549523\",\r\n"
				+ "          \"TIN\": \"967050750\",\r\n"
				+ "          \"Phone1\": \"672-418-1811\",\r\n"
				+ "          \"Phone2\": \"242-244-8446\",\r\n"
				+ "          \"Phone3\": \"366-449-9188\",\r\n"
				+ "          \"Fax\": \"168-994-3569\",\r\n"
				+ "          \"ClientProviderId\": \"619\"\r\n"
				+ "        }\r\n"
				+ "      }\r\n"
				+ "    ]\r\n"
				+ "  }\r\n"
				+ "}";
		return payLoad;
		
	}

	

	

}


